### ISSUE TITLE
make TAG readonly

### ISSUE THREAD

**Issue by mamromer** [romellfudi/FudiNFC#4]
Hi, can you give me a hint how to make the tag readonly after writing? Help is appreciated.

**Comment by romellfudi** [comment]
@mamromer Implement onNewIntent on your activity. Meanwhile your activity is on resume state, the activity will catch the event.

**Comment by mamromer** [comment]
Hi Romell, thanks for your answer. I have the onNewIntent implemented and writing of the Tag works fine, and so is reading the tag. But I don't know how to make the tag read only after writing to it.

**Comment by romellfudi** [comment]
Hello @mamromer  again.
- [X] Well you must set a password/pin in order to avoid rewriting before starting writing
- [X]  The simple way to use a tag makes not possible to stop rewriting.
- [X] I suggest you searching for setting up tags and providing security them.

**Comment by romellfudi** [comment]
Even though your tag can write and read, not every tag has protection.

**Comment by mamromer** [comment]
OK, I understand. I will dive into it. Thanks!

**Comment by romellfudi** [comment]
The normal flow is that application only can read for short time and while a UI dialog displays an animated slide such as [little](github.com/airbnb/lottie-android)
