### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by zigapovhe** [romellfudi/FudiNFC#7]
App with your library crashes on Android 12 with "`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`"

**Comment by romellfudi** [comment]
Does it happen in both versions java and kotlin?

**Comment by romellfudi** [comment]
Please write the whole exception as to modify FLAGs

**Comment by zigapovhe** [comment]
You must [specify the mutability](https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent) of each [PendingIntent](https://developer.android.com/reference/android/app/PendingIntent) object that your app creates. This additional requirement improves app's security. That's why you must add PendingIntent.FLAG_MUTABLE or PendingIntent.FLAG_IMMUTABLE to every PendingIntent.  Also don't forget to add android:exported="true"/android:exported="false" lines in your manifest for each intent-filter and for all activity tags.

**Comment by romellfudi** [comment]
Thanks please send a pull Request to merge ASAP @zigapovhe

**Comment by romellfudi** [comment]
Hi @zigapovhe , I've read your email, please send your PR with only code to check it.

**Comment by zigapovhe** [comment]
Here is the PR: https://github.com/romellfudi/FudiNFC/pull/8

**Comment by romellfudi** [comment]
This issue was solved in #8
